theme: jekyll-theme-dinky
title: andre menegazzo
author: andrmng 
email: andremenegazzo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  ğŸ‘¨ğŸ»â€ğŸš€ğŸŒ€ğŸ•¹ï¸
# social links
twitter_username: andrmng # DO NOT include the @ character, or else the build will fail!
github_username:  andrmng # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
